[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "openhands-ai"
version = "0.38.0"
description = "OpenHands: Code Less, Make More"
authors = [
  { name = "OpenHands" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
  "litellm>=1.60.0,<2.0.0,!=1.64.4,!=1.67.*",
  "aiohttp>=3.9.0,!=3.11.13",
  "google-generativeai",
  "google-api-python-client>=2.164.0,<3.0.0",
  "google-auth-httplib2",
  "google-auth-oauthlib",
  "termcolor",
  "docker",
  "fastapi",
  "toml",
  "uvicorn",
  "types-toml",
  "numpy",
  "json-repair",
  "browsergym-core==0.13.3",
  "html2text",
  "e2b>=1.0.5,<1.4.0",
  "pexpect",
  "jinja2>=3.1.3,<4.0.0",
  "python-multipart",
  "boto3",
  "minio>=7.2.8,<8.0.0",
  "tenacity>=8.5,<10.0",
  "zope-interface==7.2",
  "pathspec>=0.12.1,<0.13.0",
  "google-cloud-aiplatform",
  "anthropic[vertex]",
  "tree-sitter>=0.24.0,<0.25.0",
  "bashlex>=0.18,<0.19",
  "pyjwt>=2.9.0,<3.0.0",
  "dirhash",
  "python-frontmatter>=1.1.0,<2.0.0",
  "python-docx",
  "PyPDF2",
  "python-pptx",
  "pylatexenc",
  "tornado",
  "python-dotenv",
  "pylcs>=0.1.1,<0.2.0",
  "whatthepatch>=1.0.6,<2.0.0",
  "protobuf>=4.21.6,<5.0.0",
  "opentelemetry-api==1.25.0",
  "opentelemetry-exporter-otlp-proto-grpc==1.25.0",
  "modal>=0.66.26,<0.78.0",
  "runloop-api-client==0.32.0",
  "libtmux>=0.37,<0.40",
  "pygithub>=2.5.0,<3.0.0",
  "joblib",
  "openhands-aci==0.2.13",
  "python-socketio>=5.11.4,<6.0.0",
  "redis>=5.2,<7.0",
  "sse-starlette>=2.1.3,<3.0.0",
  "psutil",
  "stripe>=11.5,<13.0",
  "ipywidgets>=8.1.5,<9.0.0",
  "qtconsole>=5.6.1,<6.0.0",
  "memory-profiler>=0.61.0,<0.62.0",
  "aiodocker",
  "pydantic-settings",
  "daytona-sdk==0.16.1",
  "daytona-api-client==0.18.1",
  "mcp==1.7.1",
  "python-json-logger>=3.2.1,<4.0.0",
  "prompt-toolkit>=3.0.50,<4.0.0",
  "mcpm==1.9.0",
  "anyio==4.9.0",
  "pythonnet",
]

[project.urls]
Repository = "https://github.com/All-Hands-AI/OpenHands"

[project.scripts]
openhands = "openhands.core.cli:main"

[tool.hatch.build.targets.wheel]
packages = [ "openhands" ]

[tool.hatch.build.targets.wheel.force-include]
"pyproject.toml" = "openhands/pyproject.toml"
"uv.lock" = "openhands/uv.lock"

[tool.hatch.build.targets.sdist]
include = [
  "openhands",
  "pyproject.toml",
  "uv.lock",
  "README.md",
  "LICENSE",
  "MANIFEST.in",
]

[dependency-groups]
dev = [
  "uv",
  "ruff==0.11.9",
  "mypy==1.15.0",
  "pre-commit==4.2.0",
  "build",
]
runtime-core = [
  "binaryornot",
  "fastapi",
  "python-multipart",
  "uvicorn",
  "pydantic",
  "json-repair",
  "termcolor",
  "python-json-logger>=3.2.1",
  "bashlex>=0.18",
  "libtmux>=0.37,<0.40",
  "psutil",
  "tenacity>=8.5,<10.0",
  "openai",
  "openhands-aci==0.2.13",
  "chardet",
  "networkx",
  "rank-bm25>=0.2.0,<1.0.0",
  "python-docx",
  "PyPDF2",
  "python-pptx",
  "pylatexenc",
  "mcp==1.7.1",
  "mcpm==1.9.0",
]
runtime = [
  "chardet",
  "networkx",
  "rank-bm25>=0.2.0,<1.0.0",
  "jupyterlab",
  "notebook",
  "jupyter-kernel-gateway",
  "flake8",
  "playwright",
]
test = [
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "pytest-forked",
  "pytest-xdist",
  "openai",
  "pandas",
  "reportlab",
  "gevent>=24.2.1,<26.0.0",
]
evaluation = [
  "streamlit",
  "whatthepatch",
  "retry",
  "evaluate",
  "swebench>=3.0.8,<4.0.0",
  "swegym @ git+https://github.com/SWE-Gym/SWE-Bench-Package.git",
  "commit0",
  "func-timeout",
  "sympy",
  "gdown",
  "matplotlib",
  "seaborn",
  "tabulate",
  "browsergym==0.13.3",
  "browsergym-webarena==0.13.3",
  "browsergym-miniwob==0.13.3",
  "browsergym-visualwebarena==0.13.3",
  "boto3-stubs[s3]>=1.37.19,<2.0.0",
  "pyarrow==20.0.0",
  "datasets",
]
testgeneval = [
  "fuzzywuzzy>=0.18.0,<0.19.0",
  "rouge>=1.0.1,<2.0.0",
  "python-levenshtein>=0.26.1,<0.28.0",
  "tree-sitter-python>=0.23.6,<0.24.0",
]

[tool.autopep8]
# autopep8 fights with mypy on line length issue
ignore = [ "E501" ]

[tool.black]
# prevent black (if installed) from changing single quotes to double quotes
skip-string-normalization = true

[tool.ruff]
lint.select = [ "D" ]
# ignore warnings for missing docstrings
lint.ignore = [ "D1" ]
lint.pydocstyle.convention = "google"

[tool.coverage.run]
concurrency = [ "gevent" ]
